In [1]:
import torch
import numpy as np
from torch.utils.data import TensorDataset, DataLoader

In [2]:
import pandas as pd

In [3]:
train_ds_pd = pd.read_csv('train.csv', dtype = 'float32')
print(train_ds_pd)

        ID      crim    zn  indus  chas    nox     rm         age     dis  \
0      1.0   0.00632  18.0   2.31   0.0  0.538  6.575   65.199997  4.0900   
1      2.0   0.02731   0.0   7.07   0.0  0.469  6.421   78.900002  4.9671   
2      4.0   0.03237   0.0   2.18   0.0  0.458  6.998   45.799999  6.0622   
3      5.0   0.06905   0.0   2.18   0.0  0.458  7.147   54.200001  6.0622   
4      7.0   0.08829  12.5   7.87   0.0  0.524  6.012   66.599998  5.5605   
5     11.0   0.22489  12.5   7.87   0.0  0.524  6.377   94.300003  6.3467   
6     12.0   0.11747  12.5   7.87   0.0  0.524  6.009   82.900002  6.2267   
7     13.0   0.09378  12.5   7.87   0.0  0.524  5.889   39.000000  5.4509   
8     14.0   0.62976   0.0   8.14   0.0  0.538  5.949   61.799999  4.7075   
9     15.0   0.63796   0.0   8.14   0.0  0.538  6.096   84.500000  4.4619   
10    16.0   0.62739   0.0   8.14   0.0  0.538  5.834   56.500000  4.4986   
11    17.0   1.05393   0.0   8.14   0.0  0.538  5.935   29.299999  4.4986   

In [4]:
train_ds1= torch.Tensor(train_ds_pd.values)
print(train_ds1)

tensor([[1.0000e+00, 6.3200e-03, 1.8000e+01,  ..., 3.9690e+02, 4.9800e+00,
         2.4000e+01],
        [2.0000e+00, 2.7310e-02, 0.0000e+00,  ..., 3.9690e+02, 9.1400e+00,
         2.1600e+01],
        [4.0000e+00, 3.2370e-02, 0.0000e+00,  ..., 3.9463e+02, 2.9400e+00,
         3.3400e+01],
        ...,
        [5.0300e+02, 4.5270e-02, 0.0000e+00,  ..., 3.9690e+02, 9.0800e+00,
         2.0600e+01],
        [5.0400e+02, 6.0760e-02, 0.0000e+00,  ..., 3.9690e+02, 5.6400e+00,
         2.3900e+01],
        [5.0600e+02, 4.7410e-02, 0.0000e+00,  ..., 3.9690e+02, 7.8800e+00,
         1.1900e+01]])


In [5]:
inputs = train_ds1[:,0:14]
print(inputs.shape)

torch.Size([333, 14])


In [6]:
import torch.nn as nn

In [7]:
model = nn.Linear(14, 1)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1506,  0.0636,  0.2652,  0.0546,  0.0732,  0.0234, -0.1640, -0.2246,
          0.2357,  0.2668,  0.1176,  0.1593, -0.1748, -0.2445]],
       requires_grad=True)
Parameter containing:
tensor([-0.1394], requires_grad=True)


In [8]:
preds = model(inputs)
print(preds)

tensor([[-4.2920e+01],
        [-5.6829e+01],
        [-4.9226e+01],
        [-5.1965e+01],
        [-4.1821e+01],
        [-4.8728e+01],
        [-4.5003e+01],
        [-3.4635e+01],
        [-4.2167e+01],
        [-4.4734e+01],
        [-4.0533e+01],
        [-3.2268e+01],
        [-1.7854e+01],
        [-4.8944e+01],
        [-4.7866e+01],
        [-5.0250e+01],
        [-5.1768e+01],
        [-3.2562e+01],
        [-4.3989e+01],
        [-4.5779e+01],
        [-2.4055e+01],
        [-3.4823e+01],
        [-1.5622e+01],
        [-1.3620e+01],
        [-3.1797e+01],
        [-3.3967e+01],
        [-4.0949e+01],
        [-4.0960e+01],
        [-4.1676e+01],
        [-5.3557e+01],
        [-4.7906e+01],
        [-3.6318e+01],
        [-3.8820e+01],
        [-2.9423e+01],
        [ 4.6400e+00],
        [-1.1443e+01],
        [-6.5577e+00],
        [-8.8574e+00],
        [-2.1351e+01],
        [-3.1745e+01],
        [-3.5173e+01],
        [-2.5353e+01],
        [-3.9523e+01],
        [ 4

In [9]:
targets = train_ds1[:,14:15]
print(targets.shape)
print(targets)

torch.Size([333, 1])
tensor([[24.0000],
        [21.6000],
        [33.4000],
        [36.2000],
        [22.9000],
        [15.0000],
        [18.9000],
        [21.7000],
        [20.4000],
        [18.2000],
        [19.9000],
        [23.1000],
        [20.2000],
        [13.6000],
        [19.6000],
        [15.2000],
        [14.5000],
        [14.8000],
        [12.7000],
        [14.5000],
        [13.5000],
        [24.7000],
        [30.8000],
        [34.9000],
        [25.3000],
        [24.7000],
        [21.2000],
        [19.3000],
        [20.0000],
        [16.6000],
        [19.4000],
        [19.7000],
        [20.5000],
        [23.4000],
        [18.9000],
        [35.4000],
        [24.7000],
        [31.6000],
        [23.3000],
        [18.7000],
        [16.0000],
        [25.0000],
        [33.0000],
        [23.5000],
        [19.4000],
        [22.0000],
        [17.4000],
        [24.2000],
        [22.8000],
        [23.4000],
        [24.1000],
        [2

In [10]:
train_ds = TensorDataset(inputs, targets)

In [11]:
batch_size = 10
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [12]:
import torch.nn.functional as F
loss_fn = F.mse_loss

In [13]:
loss = loss_fn(preds, targets)
print(loss)

tensor(2473.3535, grad_fn=<MseLossBackward>)


In [14]:
opt = torch.optim.SGD(model.parameters(), lr = 0.00000141)

In [15]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[1.1000e+01, 2.2489e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
         6.3770e+00, 9.4300e+01, 6.3467e+00, 5.0000e+00, 3.1100e+02, 1.5200e+01,
         3.9252e+02, 2.0450e+01],
        [4.6100e+02, 4.8121e+00, 0.0000e+00, 1.8100e+01, 0.0000e+00, 7.1300e-01,
         6.7010e+00, 9.0000e+01, 2.5975e+00, 2.4000e+01, 6.6600e+02, 2.0200e+01,
         2.5523e+02, 1.6420e+01],
        [1.7600e+02, 6.6640e-02, 0.0000e+00, 4.0500e+00, 0.0000e+00, 5.1000e-01,
         6.5460e+00, 3.3100e+01, 3.1323e+00, 5.0000e+00, 2.9600e+02, 1.6600e+01,
         3.9096e+02, 5.3300e+00],
        [1.5400e+02, 2.1492e+00, 0.0000e+00, 1.9580e+01, 0.0000e+00, 8.7100e-01,
         5.7090e+00, 9.8500e+01, 1.6232e+00, 5.0000e+00, 4.0300e+02, 1.4700e+01,
         2.6195e+02, 1.5790e+01],
        [4.1400e+02, 2.8656e+01, 0.0000e+00, 1.8100e+01, 0.0000e+00, 5.9700e-01,
         5.1550e+00, 1.0000e+02, 1.5894e+00, 2.4000e+01, 6.6600e+02, 2.0200e+01,
         2.1097e+02, 2.0080e+01],
        [1.6000e+02,

In [16]:
def fit(num_epochs, model, loss_fn, opt):
    for i in range(num_epochs):
        for xb, yb in train_dl:
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
            
        if (i+1)%10 == 0:
            print('Epoch : [{}/{}], Loss = {:.4f}'.format(i+1, num_epochs, loss.item()))
                
            

In [17]:
fit(100, model, loss_fn, opt)

Epoch : [10/100], Loss = 12.9064
Epoch : [20/100], Loss = 61.3604
Epoch : [30/100], Loss = 337.2919
Epoch : [40/100], Loss = 223.3392
Epoch : [50/100], Loss = 61.8698
Epoch : [60/100], Loss = 32.5753
Epoch : [70/100], Loss = 66.1215
Epoch : [80/100], Loss = 10.7681
Epoch : [90/100], Loss = 10.2702
Epoch : [100/100], Loss = 12.3680


In [18]:
print(model(inputs))

tensor([[24.3391],
        [23.5539],
        [23.5986],
        [23.5219],
        [22.3907],
        [21.7940],
        [23.7022],
        [18.6672],
        [22.8529],
        [23.1603],
        [22.2500],
        [20.2582],
        [14.2945],
        [20.1304],
        [22.7915],
        [21.3925],
        [21.6167],
        [17.5877],
        [18.6068],
        [23.3531],
        [14.3074],
        [19.4585],
        [30.5692],
        [30.8904],
        [18.9702],
        [18.8863],
        [20.6986],
        [20.1919],
        [18.6980],
        [21.2834],
        [20.6204],
        [22.8748],
        [25.7183],
        [22.7685],
        [27.3365],
        [33.8191],
        [32.2376],
        [35.8542],
        [25.4431],
        [26.3537],
        [27.2461],
        [25.9037],
        [26.2791],
        [30.0074],
        [29.1320],
        [20.9071],
        [20.4312],
        [18.4867],
        [19.4170],
        [17.8855],
        [17.7497],
        [19.7368],
        [20.

In [19]:
print(targets)

tensor([[24.0000],
        [21.6000],
        [33.4000],
        [36.2000],
        [22.9000],
        [15.0000],
        [18.9000],
        [21.7000],
        [20.4000],
        [18.2000],
        [19.9000],
        [23.1000],
        [20.2000],
        [13.6000],
        [19.6000],
        [15.2000],
        [14.5000],
        [14.8000],
        [12.7000],
        [14.5000],
        [13.5000],
        [24.7000],
        [30.8000],
        [34.9000],
        [25.3000],
        [24.7000],
        [21.2000],
        [19.3000],
        [20.0000],
        [16.6000],
        [19.4000],
        [19.7000],
        [20.5000],
        [23.4000],
        [18.9000],
        [35.4000],
        [24.7000],
        [31.6000],
        [23.3000],
        [18.7000],
        [16.0000],
        [25.0000],
        [33.0000],
        [23.5000],
        [19.4000],
        [22.0000],
        [17.4000],
        [24.2000],
        [22.8000],
        [23.4000],
        [24.1000],
        [21.4000],
        [20.

In [20]:
loss = loss_fn(model(inputs), targets)

In [21]:
print(loss)

tensor(58.6850, grad_fn=<MseLossBackward>)


In [22]:
diff_matrix = abs(model(inputs) - targets)
accu_sum = diff_matrix.sum()
accuracy = (accu_sum/diff_matrix.numel())

In [23]:
print(accuracy)

tensor(5.6525, grad_fn=<DivBackward0>)


In [24]:
test_ds_pd = pd.read_csv('test.csv', dtype = 'float32')
print(test_ds_pd)

        ID       crim    zn  indus  chas    nox     rm         age     dis  \
0      3.0   0.027290   0.0   7.07   0.0  0.469  7.185   61.099998  4.9671   
1      6.0   0.029850   0.0   2.18   0.0  0.458  6.430   58.700001  6.0622   
2      8.0   0.144550  12.5   7.87   0.0  0.524  6.172   96.099998  5.9505   
3      9.0   0.211240  12.5   7.87   0.0  0.524  5.631  100.000000  6.0821   
4     10.0   0.170040  12.5   7.87   0.0  0.524  6.004   85.900002  6.5921   
5     18.0   0.784200   0.0   8.14   0.0  0.538  5.990   81.699997  4.2579   
6     20.0   0.725800   0.0   8.14   0.0  0.538  5.727   69.500000  3.7965   
7     25.0   0.750260   0.0   8.14   0.0  0.538  5.924   94.099998  4.3996   
8     26.0   0.840540   0.0   8.14   0.0  0.538  5.599   85.699997  4.4546   
9     27.0   0.671910   0.0   8.14   0.0  0.538  5.813   90.300003  4.6820   
10    29.0   0.772990   0.0   8.14   0.0  0.538  6.495   94.400002  4.4547   
11    30.0   1.002450   0.0   8.14   0.0  0.538  6.674   87.3000

In [25]:
test_ds = torch.tensor(test_ds_pd.values)
print(test_ds)

tensor([[3.0000e+00, 2.7290e-02, 0.0000e+00,  ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        [6.0000e+00, 2.9850e-02, 0.0000e+00,  ..., 1.8700e+01, 3.9412e+02,
         5.2100e+00],
        [8.0000e+00, 1.4455e-01, 1.2500e+01,  ..., 1.5200e+01, 3.9690e+02,
         1.9150e+01],
        ...,
        [4.9900e+02, 2.3912e-01, 0.0000e+00,  ..., 1.9200e+01, 3.9690e+02,
         1.2920e+01],
        [5.0100e+02, 2.2438e-01, 0.0000e+00,  ..., 1.9200e+01, 3.9690e+02,
         1.4330e+01],
        [5.0500e+02, 1.0959e-01, 0.0000e+00,  ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00]])


In [26]:
test_ds.shape

torch.Size([173, 14])

In [31]:
predictions = model(test_ds)

In [33]:
np.savetxt('predictions1.csv',predictions.detach().numpy(), delimiter = ',', header = 'Predictions : Boston Housing Dataset')
